-- ---------------------------------------------------------------------------
-- Catálogo de repuestos Groupe SEB — esquema inicial (Postgres / Supabase)
--
-- Dos capas, y esa separación es el corazón del diseño:
--
--   BASE     tablas que escribe el pipeline de Python (PDF + API AgoraPlus).
--   OVERRIDE tablas que sólo escribe una persona desde /admin.
--            El importador NUNCA las abre, así que una edición manual no se
--            puede perder por un upsert descuidado: la protección es una
--            frontera de tablas, no una regla que alguien deba recordar.
--
-- Cuando el pipeline cambia un valor que además fue editado a mano, no gana
-- nadie en silencio: v_drift lo saca a una cola de revisión.
--
-- Cifras reales verificadas sobre public/data/catalog.json:
--   552 modelos · 1737 repuestos · 18 familias (15 en modelos + 3 sólo en
--   repuestos) · 8 marcas · 834 láminas · 1646 repuestos con precio.
-- ---------------------------------------------------------------------------

-- ============================================================ utilidades

-- `default now()` sólo dispara en INSERT, y los upsert de PostgREST llegan
-- como INSERT ... ON CONFLICT DO UPDATE: sin esto las marcas de tiempo
-- quedarían congeladas en la primera carga.
create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================================================== catálogos base
-- `by default as identity` (no `always`): así un upsert de PostgREST que
-- traiga id no revienta con SQLSTATE 428C9.

create table if not exists brand (
  id    smallint generated by default as identity primary key,
  name  text not null unique,
  color text                       -- el punto de color de la insignia
);

create table if not exists family (
  id         smallint generated by default as identity primary key,
  name       text not null unique,
  sort_order smallint not null default 500
);

-- Semilla con la UNIÓN de familias de modelos y de repuestos. Las tres
-- últimas existen SÓLO en repuestos (24 en total) y no aparecen en
-- catalog.families, que consolidate.py deriva únicamente de los modelos:
-- sin ellas el primer INSERT de repuestos moría con un 23503.
insert into family (name, sort_order) values
  ('Arroceras', 10), ('Aspiradoras', 20), ('Batidoras', 30), ('Cafeteras', 40),
  ('Calefactor', 50), ('Freidoras', 60), ('Hornos', 70), ('Licuadoras', 80),
  ('Ollas a presion', 90), ('Picadora', 100), ('Planchas de Ropa', 110),
  ('Sandwichera y tostador', 120), ('Tapas de vidrio', 130), ('Ventiladores', 140),
  ('Accesorios', 200), ('Accesorios de coccion', 210), ('Picatodos y exprimidores', 220),
  ('Otros', 999)
on conflict (name) do nothing;

insert into brand (name) values
  ('IMUSA'), ('KRUPS'), ('LAGOSTINA'), ('MOULINEX'),
  ('ROWENTA'), ('SAMURAI'), ('T-FAL'), ('UMCO')
on conflict (name) do nothing;

-- Procedencia del catálogo (Catalog.generatedFrom en el contrato TS).
create table if not exists catalog_meta (
  id             boolean primary key default true check (id),  -- fila única
  generated_from text[] not null default '{}',
  generated_at   timestamptz not null default now()
);
insert into catalog_meta (id) values (true) on conflict (id) do nothing;

-- =============================================================== capa BASE

create table if not exists model (
  id              text primary key,
  name            text not null,
  brand_id        smallint references brand(id),
  family_id       smallint references family(id),
  ref             text,               -- 43 de 552 lo traen null: no es clave
  brand_origin    text check (brand_origin in ('read', 'derived')),
  sources         text[] not null default '{}',
  equivalent_refs text[] not null default '{}',
  retired_at      timestamptz,        -- baja lógica; ver v_drift
  imported_at     timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists model_family_idx on model (family_id);
create index if not exists model_brand_idx  on model (brand_id);
create index if not exists model_ref_idx    on model (ref) where ref is not null;

create table if not exists part (
  code          text primary key,
  -- cmmf y ean NO son únicos en los datos reales (33 cmmf repetidos en 70
  -- filas, 3 ean en 6). Declararlos unique aborta la importación.
  cmmf          text,
  ean           text,
  description   text not null,
  -- `ue` llega como número o como string, pero los 114 valores string son
  -- todos numéricos, así que una sola columna entera los cubre.
  ue            integer,
  uc_master     text,
  family_id     smallint references family(id),
  product_line  text,
  brand_id      smallint references brand(id),
  sources       text[] not null default '{}',
  photo         text,
  photo_width   integer,
  photo_height  integer,
  -- Enteros en COP. price_gross es idéntico a price_regular en los 1646
  -- repuestos con precio; se conserva por si una lista futura los separa.
  price_regular integer,
  price_gross   integer,
  currency      text,
  retired_at    timestamptz,
  imported_at   timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists part_cmmf_idx   on part (cmmf) where cmmf is not null;
create index if not exists part_ean_idx    on part (ean)  where ean  is not null;
create index if not exists part_family_idx on part (family_id);

-- Un mismo código se repite dentro de un modelo, por eso la fila tiene
-- identidad propia. El FK a part existe: hoy no hay ni un código huérfano
-- (verificado), y sin él un huérfano produciría un `part` undefined en el
-- JSON exportado, que el front no espera.
create table if not exists model_part (
  row_id   text primary key,
  model_id text not null references model(id) on delete cascade,
  code     text not null references part(code) on delete restrict,
  hotspot  jsonb,
  position smallint not null default 0
);

create index if not exists model_part_model_idx on model_part (model_id);
create index if not exists model_part_code_idx  on model_part (code);

create table if not exists diagram (
  id       bigint generated by default as identity primary key,
  model_id text not null references model(id) on delete cascade,
  -- Índice dentro de Model.diagrams[]. Hotspot.diagram apunta AQUÍ, y en 100
  -- modelos `plate` se repite entre láminas, así que plate NO sirve de orden.
  position smallint not null,
  image    text not null,
  width    integer,
  height   integer,
  -- Número de lámina impresa. Llega a 4 en los datos reales.
  plate    smallint not null default 1 check (plate between 1 and 8),
  -- Clave natural: hace la importación idempotente (una segunda corrida
  -- actualiza en vez de duplicar).
  unique (model_id, position)
);

create index if not exists diagram_model_idx on diagram (model_id);

-- =========================================================== capa OVERRIDE
--
-- Sólo /admin escribe aquí. Se guarda el valor humano Y el que el pipeline
-- tenía al momento de editar (base_*): esa foto es lo que después permite
-- detectar divergencia. Revisar una divergencia = re-tomar la foto, y con eso
-- la fila sale sola de la cola.

create table if not exists model_override (
  model_id       text primary key references model(id) on delete restrict,
  name           text,
  family_id      smallint references family(id),
  base_name      text,
  base_family_id smallint,
  edited_by      text,
  edited_at      timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists part_override (
  code             text primary key references part(code) on delete restrict,
  description      text,
  family_id        smallint references family(id),
  base_description text,
  base_family_id   smallint,
  edited_by        text,
  edited_at        timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- Imágenes subidas desde /admin a R2.
create table if not exists image (
  id          bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('model', 'part')),
  entity_id   text not null,
  bucket      text not null default 'groupe-seb-images',
  storage_key text not null,
  width       integer,
  height      integer,
  -- No nulo: el proyecto exige WCAG AA, y una imagen sin alternativa textual
  -- no lo cumple. Cadena vacía = decorativa, que es una decisión explícita.
  alt_text    text not null default '',
  sort_order  smallint not null default 0,
  sha256      text,
  uploaded_by text,
  uploaded_at timestamptz not null default now(),
  deleted_at  timestamptz,
  -- Idempotencia: resubir el mismo archivo actualiza, no duplica.
  unique (bucket, storage_key)
);

create index if not exists image_entity_idx on image (entity_type, entity_id)
  where deleted_at is null;

-- ================================================================ triggers

create trigger model_touch          before update on model
  for each row execute function touch_updated_at();
create trigger part_touch           before update on part
  for each row execute function touch_updated_at();
create trigger model_override_touch before update on model_override
  for each row execute function touch_updated_at();
create trigger part_override_touch  before update on part_override
  for each row execute function touch_updated_at();

-- ================================================== vistas de exportación
-- security_invoker: sin esto la vista corre con los permisos de su dueño
-- (postgres) y se salta el RLS de las tablas de abajo, que es justo lo que
-- Supabase marca como SECURITY DEFINER en su linter.

create or replace view v_model
with (security_invoker = true) as
select
  m.id,
  coalesce(o.name, m.name)                       as name,
  b.name                                         as brand,
  coalesce(fo.name, f.name)                      as family,
  m.ref,
  m.brand_origin,
  m.sources,
  m.equivalent_refs,
  (o.model_id is not null)                       as edited
from model m
left join model_override o on o.model_id = m.id
left join brand  b  on b.id  = m.brand_id
left join family f  on f.id  = m.family_id
left join family fo on fo.id = o.family_id
where m.retired_at is null;

create or replace view v_part
with (security_invoker = true) as
select
  p.code,
  p.cmmf,
  p.ean,
  coalesce(o.description, p.description)         as description,
  p.ue, p.uc_master,
  coalesce(fo.name, f.name)                      as family,
  p.product_line,
  b.name                                         as brand,
  p.sources,
  p.photo, p.photo_width, p.photo_height,
  p.price_regular, p.price_gross, p.currency,
  (o.code is not null)                           as edited
from part p
left join part_override o on o.code = p.code
left join brand  b  on b.id  = p.brand_id
left join family f  on f.id  = p.family_id
left join family fo on fo.id = o.family_id
where p.retired_at is null;

-- Imágenes vigentes, listas para adjuntar al JSON exportado.
create or replace view v_image
with (security_invoker = true) as
select entity_type, entity_id, bucket, storage_key, width, height, alt_text, sort_order
from image
where deleted_at is null
order by entity_type, entity_id, sort_order;

-- Cola de revisión. Cuatro motivos, no uno:
--  · el pipeline movió un nombre/descripción editada a mano
--  · el pipeline reclasificó una familia editada a mano (recategorize.py lo
--    hace de forma rutinaria)
--  · el pipeline dio de baja una fila que tiene trabajo humano encima; el
--    retiro es un UPDATE, así que no dispara el RESTRICT y desaparecería del
--    export sin avisar
create or replace view v_drift
with (security_invoker = true) as
select 'model' as entity, m.id as entity_id, 'name' as field,
       o.base_name as value_at_edit, m.name as pipeline_now, o.name as human_value,
       o.edited_at, null::timestamptz as retired_at
from model_override o join model m on m.id = o.model_id
where o.name is not null and o.base_name is distinct from m.name and m.retired_at is null
union all
select 'model', m.id, 'family',
       fb.name, f.name, fo.name, o.edited_at, null::timestamptz
from model_override o
join model m on m.id = o.model_id
left join family fb on fb.id = o.base_family_id
left join family f  on f.id  = m.family_id
left join family fo on fo.id = o.family_id
where o.family_id is not null and o.base_family_id is distinct from m.family_id and m.retired_at is null
union all
select 'part', p.code, 'description',
       o.base_description, p.description, o.description, o.edited_at, null::timestamptz
from part_override o join part p on p.code = o.code
where o.description is not null and o.base_description is distinct from p.description and p.retired_at is null
union all
select 'model', m.id, 'retired', o.base_name, null, o.name, o.edited_at, m.retired_at
from model_override o join model m on m.id = o.model_id
where m.retired_at is not null
union all
select 'part', p.code, 'retired', o.base_description, null, o.description, o.edited_at, p.retired_at
from part_override o join part p on p.code = o.code
where p.retired_at is not null;

-- ================================================================== acceso
-- Todo el tráfico entra por el Worker con la service_role key, que se salta
-- RLS. RLS sin políticas = denegar por defecto para anon/authenticated.

alter table brand          enable row level security;
alter table family         enable row level security;
alter table catalog_meta   enable row level security;
alter table model          enable row level security;
alter table part           enable row level security;
alter table model_part     enable row level security;
alter table diagram        enable row level security;
alter table model_override enable row level security;
alter table part_override  enable row level security;
alter table image          enable row level security;

grant usage on schema public to service_role;
grant all privileges on all tables    in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

-- Las vistas no heredan el RLS de sus tablas: hay que revocarlas explícitamente
-- o quedarían legibles para cualquiera con la anon key, incluida v_drift.
revoke all on v_model, v_part, v_image, v_drift from anon, authenticated;

-- Y que lo anterior no sea una foto fija: cualquier tabla futura nace con los
-- permisos correctos sin tener que acordarse.
alter default privileges in schema public
  grant all privileges on tables to service_role;
alter default privileges in schema public
  grant all privileges on sequences to service_role;
alter default privileges in schema public
  revoke all on tables from anon, authenticated;
